### PR TITLE
Simulator dask array

### PR DESCRIPTION
**Pull request by fnattino**
Dask-array-based implementation of the parallelism of simulations, allowing for workers to read parameters from and write output to the store.

### CODE REVIEW

**Comment by fnattino** [comment]
Left to do:
- [x] fix `MemoryStore` and `DirectoryStore` (missing updates after the refactoring);
- [x] reactivate tests created before the refactoring;
- [x] add tests to verify that simultaneous processes can grow the cache;
- [x] add tests to verify that simulations can be executed (a)synchronously;
- [x] fix default behaviour if Dask cluster is not set
- [x] clean up unused methods in `Store`
- [x] optionally set Zarr chunking strategy?

**Comment by fnattino** [comment]
Anything else @rogerkuou?

**Comment by rogerkuou** [comment]
Hi Francesco, I fixed some issues you listed in PR #3. I think these points are already quite sufficient.

**Comment by fnattino** [comment]
Thanks @rogerkuou , I am going to add the two additional tests and the possibility of specifying the store chunking strategy from input.

**Comment by fnattino** [comment]
Merged directly to the upstream: https://github.com/undark-lab/swyft/pull/21

**Pull request closed without merging**
